# Generated by Django 2.0 on 2018-01-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor_User', models.CharField(max_length=30, unique=True)),
                ('Autor_Name', models.CharField(max_length=30)),
                ('Autor_Mail', models.CharField(max_length=30, unique=True)),
                ('Autor_Phone', models.CharField(max_length=20, unique=True)),
                ('Autor_Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(max_length=50, unique=True)),
                ('Post_Content', models.TextField()),
                ('Post_Creation_Date', models.DateField()),
                ('Post_About', models.TextField()),
                ('Post_About_Short', models.CharField(max_length=100)),
                ('Post_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
                ('Post_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
